package com.lurenjia534.myapplication.deviceInfo

data class DeviceDetails(
    val deviceName: String,
    val deviceManufacturer: String,
    val deviceVersion: String,
    val deviceSDK: Int,
    val deviceBrand: String,
    val deviceProduct: String,
    val deviceBoard: String,
    val deviceHardware: String,
    val deviceFingerprint: String,
    val deviceHost: String,
    val deviceID: String,
    val deviceTags: String,
    val deviceType: String,
    val deviceUser: String,
    val deviceDisplay: String,
    val deviceBootloader: String,
    val deviceRadio: String,
    val deviceSerial: String,
    val deviceTime: Long,
    val deviceSecurityPatch: String,
    val deviceCodename: String,
    val deviceIncremental: String,
    val deviceBaseOS: String,
    val deviceVersionCodeName: String,
    val deviceVersionRelease: String,
    val deviceVersionSDK: Int,
    val deviceVersionSecurityPatch: String,
    val deviceVersionIncremental: String,
    val deviceVersionBaseOS: String,
    val deviceVersionPreviewSDK: Int
)